import "@/app/ui/global.css"
import { inter } from "./ui/fonts";
import { Metadata } from "next";
import Link from "next/link";
export const metadata :Metadata =  {
  title:{
    absolute:"",
    default:"Next.js Tutorial - Omid",
    template:"%s | Omid",
  },
  description:"Generated by Next.js"
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <header className=" p-10 bg-blue-600">
          <Link href="/">
          <p>Header</p>
          </Link>
        </header>
        {children}
        <footer className=" p-10 bg-gray-400">
          <p>Footer</p>
        </footer>
        </body>
    </html>
  );
}
